

  function drawMap() {

    var data = new google.visualization.DataTable();

// Insert data for super polluters
    data.addColumn('number', 'Lat');
    data.addColumn('number', 'Long');
    data.addColumn({
        type: 'string',
        role: 'tooltip',
        'p': {'html': true}//added html version
    });

    var markers = data.addRows([

      
      [51.615439,-0.176323,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">London Brewing Company @The Bohemia</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.thebohemia.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon - Wed: 12pm - 11pm Thu: 12pm - 12am Fri - Sat: 12pm - 1am  Sun: 12pm - 10:30pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">London Brewing Co</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: They make up to 15 different beers on site, from Best Bitter & IPA to fruit & sour beers. There is also an onsite bottle shop</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="London Brewing Company @The Bohemia" /><input type="submit" value="Get directions" /></form></div>'],
      [51.477658,0.195528,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Bexley Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://bexleybrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Weekends only, from 12 to 3 - 4pm (check on the website)</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">BOB (Bexleys Own Beer)</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: They provide informative tours and talks on beer</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Bexley Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.414342,-0.076741,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Inkspot Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.theinkspotbrewery.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon"></p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">St.Reatham Beer</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sold at <a href http://www.theinkspotbrewery.com/inkspots> these locations </a></p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Inkspot Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.415696,-0.052657,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Late Knights Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.lateknightsbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon"></p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">http://www.lateknightsbrewery.co.uk/our-beers.html</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Might be closed...</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Late Knights Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.547029,-0.146749,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Camden Town Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.camdentownbrewery.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Thu - Sun 12pm - 11pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Camden Hells</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: You can book a tour of the brewery <a href http://www.camdentownbrewery.com/about/> here </a></p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Camden Town Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.546689,-0.157907,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The Load of Hay Taven</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://theloadofhaytavern.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Monday 3–10:30pm Tue - Wed -Thu 3–11:30pm Fri 12–11:30pm Sat 10am–11:30pm Sun 10am–10:30pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Load of Hay (cask beer)</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: 18th century pub that sells craft beers</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The Load of Hay Taven" /><input type="submit" value="Get directions" /></form></div>'],
      [51.528417,-0.118521,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The Queens Head</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://queensheadlondon.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon & Sun: 12pm - 11pm Tuesday - Saturday: 12pm - 12am </p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Local pub with a wide selection of ales, porters and stouts, most of them coming from local breweries (Kernel, Redemption, Truman’s, Camden Town etc)</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The Queens Head" /><input type="submit" value="Get directions" /></form></div>'],
      [51.384504,-0.091238,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Volden</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://volden.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon"></p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Volden Session, Pale and Juniper</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Check the <a href http://volden.co.uk/> Stocklist </a? on their web page to see where you can find their beer</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Volden" /><input type="submit" value="Get directions" /></form></div>'],
      [51.344359,-0.003798,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The Cronx</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.thecronx.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon - Sun: 11am - 11pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Cronx Kotchin</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: They have been the first non-brewpub brewer in Croydon for more than 50 years. They opened their first bar in October 2016, at Croydon BoxPark.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The Cronx" /><input type="submit" value="Get directions" /></form></div>'],
      [51.507334,-0.271879,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Dragonfly Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://dragonflybrewery.wordpress.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon – Thu: 4pm – 11pm Fri: 4pm - 12pm Sat: 12pm – 12am Sun: 12pm – 10pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Dark Matter stout</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Microbrewery at The George & Dragon Pub.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Dragonfly Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.495559,-0.305954,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Ealing Park Tavern</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://ealingparktavern.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon - Wed: 11am - 11pm Thu - Fri: 11am - 12am Sat: 11am - 12am Sun: 11am - 10.30pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Long Arm</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Ealing Park Tavern" /><input type="submit" value="Get directions" /></form></div>'],
      [51.508409,-0.275972,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Laines Brewing @Aeronaut</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.aeronaut.pub/brewery">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Sun - Wed: 12pm - 12am Thu: 12pm - 1am Fri - Sat: 12pm - 1.30am</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: The Aeronaut hosts regular nights involving acrobats and circus performers. Onsite brewery.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Laines Brewing @Aeronaut" /><input type="submit" value="Get directions" /></form></div>'],
      [51.500081,-0.338487,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Weird Beard Brew Co.</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.weirdbeardbrewco.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon"></p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;"> Mariana Trench. This is the ist of their brews: http://www.weirdbeardbrewco.com/our-beers-1/</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sold here <a href http://www.weirdbeardbrewco.com/wheretofind/#/pubs-bars-and-restaruants/> here </a></p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Weird Beard Brew Co." /><input type="submit" value="Get directions" /></form></div>'],
      [51.492206,0.074265,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Hop Stuff Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.hopstuffbrewery.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon"></p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Fusilier</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: This is not a brewpub but you can taste their beer at the <a href http://www.taproomse18.com/> Taproom </a></p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Hop Stuff Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.489497,0.007542,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Meantime Brewing Company</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://www.meantimebrewing.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon - Wed 12–10:30pm Thur - Fri : 12 - 11pm Sat: 11am–11pm Sun: 12–6pm </p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;"><a href https://www.meantimebrewing.com/visit/brewery-tour/> Here </a> you can book a brewery tour.</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Meantime Brewing Company" /><input type="submit" value="Get directions" /></form></div>'],
      [51.548664,-0.060114,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The Five Points Brewing Co.</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://fivepointsbrewing.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon"></p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Hook Island Red</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Tour: http://fivepointsbrewing.co.uk/tours/</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The Five Points Brewing Co." /><input type="submit" value="Get directions" /></form></div>'],
      [51.534731,-0.07581,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Hackney Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://hackneybrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon - Fri: 9am - 5pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">American Pale Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Hackney Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.541538,-0.037808,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Laine’s Brewing @People’s Park Tavern</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://peoplesparktavern.pub/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Sun - Thur: 12-12am Fri: 12 - 1am Sat: 11am - 2am</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Beers produced: http://peoplesparktavern.pub/post/134988484937/brewery</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: The Brew Lab is the onsite brewery in the pub.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Laine’s Brewing @People’s Park Tavern" /><input type="submit" value="Get directions" /></form></div>'],
      [51.546288,-0.055291,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Howling Hops</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://howlinghops.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Sunday to Thursday: 12 noon to 11pm; Friday & Saturday: 12 noon to midnight"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Rye Wit</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Howling Hops" /><input type="submit" value="Get directions" /></form></div>'],
      [51.538622,-0.057249,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">London Fields Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://londonfieldsbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Tuesday to Wednesday: 8 am to 4 pm; Thursday to Sunday: 8 am to midnight"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Hackney Hopster</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="London Fields Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.547263,-0.053832,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Pressure Drop Brewing</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://pressuredropbrewing.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">No direct sales</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Pale Fire</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sample the Pale Fire at a nearby pub: The Chesham Arms (http://www.cheshamarms.com/)</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Pressure Drop Brewing" /><input type="submit" value="Get directions" /></form></div>'],
      [51.524249,-0.231174,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Portobello Brewing Co.</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.portobellobrewing.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">No direct sales</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Market Porter</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sample the Market Porter at your nearest pub</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Portobello Brewing Co." /><input type="submit" value="Get directions" /></form></div>'],
      [51.591249,-0.057775,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Beavertown Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.beavertownbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Saturday: 2 pm to 8 pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Lupuloid IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Beavertown Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.575629,-0.150719,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">London Brewing Company @The Bull</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.londonbrewing.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Sunday to Thursday: 12 noon to 11pm; Friday: 12 noon to midnight; Saturday: 10 am to midnight"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Life - Lemon IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="London Brewing Company @The Bull" /><input type="submit" value="Get directions" /></form></div>'],
      [51.606384,-0.056992,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Redemption Brewing</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.redemptionbrewing.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Monday to Friday: 9 am to 6pm; Saturday & Sunday: 10.30 am to 12.30 pm"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Trinity</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Redemption Brewing" /><input type="submit" value="Get directions" /></form></div>'],
      [51.48775,-0.24996,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Fullers Brewery (aka Griffin Brewery)</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://www.fullers.co.uk/brewery">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Buy online at https://shop.fullers.co.uk/</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Olivers Island Golden Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Fullers Brewery (aka Griffin Brewery)" /><input type="submit" value="Get directions" /></form></div>'],
      [51.533883,-0.099789,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Earls Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.earlofessex.net/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Sunday to Thursday: 12 noon to 11.30 pm; Friday & Saturday: 12 noon to midnight"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Earls Saisson III</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Earls Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.543359,-0.114852,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Hammerton Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.hammertonbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Check website for monthly taproom timings</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Hammerton N1 Pale Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Hammerton Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.546318,-0.101535,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Highbury Brewhouse & Kitchen</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.brewhouseandkitchen.com/venue/highbury/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Monday to Thursday: 11 am to 11 pm; Friday & Saturday: 11 am to midnight; Sunday: 12 noon to 11pm"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">The Goalscorer</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Highbury Brewhouse & Kitchen" /><input type="submit" value="Get directions" /></form></div>'],
      [51.532058,-0.105566,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Islington Brewhouse & Kitchen</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.brewhouseandkitchen.com/venue/islington/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Monday to Thursday: 11 am to 11 pm; Friday & Saturday: 11 am to midnight; Sunday: 12 noon to 11pm"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Suffragette Ninja</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Islington Brewhouse & Kitchen" /><input type="submit" value="Get directions" /></form></div>'],
      [51.545021,-0.088352,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Solvay Society</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.solvaysociety.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">No direct sales</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Coulomb</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sample the Coulomb at nearby pubs like The Hops & Glory (http://www.hopsandglory.co.uk/) and Earl of Essex (http://www.earlofessex.net/)</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Solvay Society" /><input type="submit" value="Get directions" /></form></div>'],
      [51.525307,-0.211701,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Moncada Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.moncadabrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Thursday & Friday: 5 pm to 10.30 pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Notting Hill Blizzard (Bourbon barrel aged)</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Moncada Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.395163,-0.307617,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Big Smoke Brew Co</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.bigsmokebrew.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Monday to Thursday: 12 noon to 11 pm; Friday & Saturday: 12 noon to 11.30 pm; Sunday: 12 noon to 10.30 pm"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Underworld Milk Stout</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sample all of Big Smokes beer at The Antelope Ale & Cider House (http://www.theantelope.co.uk/)</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Big Smoke Brew Co" /><input type="submit" value="Get directions" /></form></div>'],
      [51.417117,-0.293891,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The Park Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.theparkbrewery.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">No direct sales</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Killcat Pale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Buy The Park Brewerys brews at these pubs - http://www.theparkbrewery.com/stockists/</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The Park Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.463556,-0.109525,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Brixton Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.brixtonbrewery.com/beta/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Saturday: 12 noon to 6 pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Electric IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Buy Brixtons brews online at http://www.brixtonbrewery.com/beta/shop/</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Brixton Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.448143,-0.101634,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Bullfinch Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.thebullfinchbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Thursday & Friday: 4 pm to 10 pm; Saturday & Sunday: 12 noon to 10 pm"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Rye IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Bullfinch Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.450557,-0.10015,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Canopy Beer Co.</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.canopybeer.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">"Wednesday, Thursday & Friday: 5 pm to 11 pm; Saturday: 12 noon to 11 pm; Sunday: 12 noon to 10 pm"</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Brockwell IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Canopy Beer Co." /><input type="submit" value="Get directions" /></form></div>'],
      [51.464917,-0.104113,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Clarkshaws</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.clarkshaws.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Saturday: 12 noon to 6pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Hellhound IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: All ingredients UK sourced, no artificial flavours or preservatives, no fish products used in the production process.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Clarkshaws" /><input type="submit" value="Get directions" /></form></div>'],
      [51.452666,-0.103008,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The Florence Brewery (and A Head In A Hat)</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.florencehernehill.com/brewery">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon - Wed: 11:00 am-11:00 pm, Thu: 11:00 am-12:00 am, Fri: 11:00 am-1:00 am, Sat: 10:00 am-1:00 am, Sun: 11:30 am-11:00 pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">In-house brew</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: All brewed on the little brewery kit with a mind of its own</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The Florence Brewery (and A Head In A Hat)" /><input type="submit" value="Get directions" /></form></div>'],
      [51.428277,-0.088733,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Gipsy Hill Brewing Company</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://gipsyhillbrew.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Saturday 1pm - 6pm, also at nearby Douglas Fir bar (Tuesday to Friday 4pm – 11pm, Saturday & Sunday 12pm – 11pm)</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Amber Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Gipsy Hill Brewing Company" /><input type="submit" value="Get directions" /></form></div>'],
      [51.428832,-0.089924,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The London Beer Factory</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.thelondonbeerfactory.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Friday evening and Saturday</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Chelsea Blonde</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: First brewery to release its range in 360 degree cans</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The London Beer Factory" /><input type="submit" value="Get directions" /></form></div>'],
      [51.462183,-0.036199,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Brockley Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="www.brockleybrewery.co.uk">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Friday evening 5.30 - 8.30pm & Saturday 11 am - 8.30pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Pale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: S-East London traditional Brockley Brewery</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Brockley Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.467376,0.008025,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Zerodegrees</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.zerodegrees.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Monday - Saturday | 12pm - 12am, Sunday | 12pm - 11pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Mango Beer</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Smooth beers paired with exotic pizza</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Zerodegrees" /><input type="submit" value="Get directions" /></form></div>'],
      [51.413066,-0.174188,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Wimbledon Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.wimbledonbrewery.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Monday to Friday 9am - 5pm, Saturday 11am - 4pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Head Brewer Derek Prentices 40 years experience is whats behind Wimbledon Brewerys brews</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Wimbledon Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.544207,-0.008937,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">TapEast</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.tapeast.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon - Sat: 11am - 11pm, Sun: 12 noon - 10pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Coffee in the morning</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: The house IPA is brewed using different hop combination every time.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="TapEast" /><input type="submit" value="Get directions" /></form></div>'],
      [51.470537,-0.26663,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">AB InBev</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.ab-inbev.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">No direct sales, but HQ in Luton and hub in Moorgate</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Bass (Local brand)</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Brands include Budweiser, Corona, Stella</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="AB InBev" /><input type="submit" value="Get directions" /></form></div>'],
      [51.464141,-0.272684,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Kew Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://kewbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Kew Market on Sundays 10am - 2pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Pagoda No. 4</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: The No.4 is brewed with a little-known hop called Instone.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Kew Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.445261,-0.34549,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Twickenham Fine Ales</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://twickenham-fine-ales.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Thursday 3-6pm, Friday 12-6pm, Saturday 10am-1pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Sundancer</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: The first Twickenham brewery since 1906. Sundancer won Silver in National Champion Beer of Britain awards.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Twickenham Fine Ales" /><input type="submit" value="Get directions" /></form></div>'],
      [51.498819,-0.073686,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Anspach & Hobday</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.anspachandhobday.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Taproom open Friday 5:00pm – 9:00pm, Saturday 10:30am – 17:30pm, Sunday 12:30pm – 17:00pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">The Three Threads</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: This relatively new brewery aims for complexity and character, with an always changing experimental range.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Anspach & Hobday" /><input type="submit" value="Get directions" /></form></div>'],
      [51.497443,-0.072001,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Brew By Numbers</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.brewbynumbers.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Taproom open Friday 6:00pm – 10:00pm, Saturday 11:00am – 8:00pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Berliner Weiss</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Beers of a moreish dryness that is hard to resist according to craftbeerlondon.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Brew By Numbers" /><input type="submit" value="Get directions" /></form></div>'],
      [51.469528,-0.069705,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Brick Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.brickbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Taproom open Wednesday 5pm - 9pm, Thursday & Friday 5pm - 10pm, Saturday 12 noon - 10pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Peckham Pils</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Found under an arch, as so often in London, bridging the gap between American hops and British tradition</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Brick Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.489277,-0.055227,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Fourpure Brewing Co.</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.fourpure.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Taproom open Fridays 4pm-8pm and Saturdays 11am-8pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Oatmeal Stout</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: The 1hl pilot brewery range is an opportunity to be daring, interesting and [to] keep innovating, produced in limited volumes in a mix of formats.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Fourpure Brewing Co." /><input type="submit" value="Get directions" /></form></div>'],
      [51.495786,-0.06853,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The Kernel Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.thekernelbrewery.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Saturday 9am - 2pm, bottled only</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">IPA, Centennial Simcoe Chinook Mosaic</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: These beers are bottled alive, to give them time to grow.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The Kernel Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.468035,-0.074549,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Gosnells London Mead</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.gosnells.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">No direct sales, local pubs in Peckham, see website</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">London Mead</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: For a warmer winter kick, try the Winter mead</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Gosnells London Mead" /><input type="submit" value="Get directions" /></form></div>'],
      [51.497015,-0.070317,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Old Kent Road Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://oldkentrdbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Ubrew taproom: Thursdays, Fridays, Saturdays 12PM-11PM, Sundays 12PM-7PM</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Astoria Saison</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Find them at Brockley market on a Saturday morning</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Old Kent Road Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.485141,-0.096044,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Orbit Beers</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://craftbeerlondon.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Taproom occasionally open on a Saturday, check website for announcements</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Neu Altbier</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: German inspired brewery: discover the delightful Cologne - Dusseldorf rivalry through their brews.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Orbit Beers" /><input type="submit" value="Get directions" /></form></div>'],
      [51.500629,-0.077301,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Southwark Brewing Co.</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://southwarkbrewing.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Saturdays 11am - 5pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Bermondsey Pale Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Peter Jacksons 30 years industry experience is backing this brewery. Southwark alumni John Harvard honoured among the brews.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Southwark Brewing Co." /><input type="submit" value="Get directions" /></form></div>'],
      [51.49756,-0.07037,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">UBREW</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://ubrew.cc/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">12PM-11PM THURSDAY, FRIDAY, SATURDAY 12PM-7PM SUNDAY</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Old Kent Road</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Brew your own beer!</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="UBREW" /><input type="submit" value="Get directions" /></form></div>'],
      [51.542892,-0.022219,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Crate Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://cratebrewery.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Friday & Saturday 12:00 until 00:00 (Pizzeria closes at 23:00) Sunday - Thursday 12:00 until 23:00 (Pizzeria closes at 22:00)</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Tours available to book.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Crate Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.543049,-0.023142,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Howling Hops Tank Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://howlinghops.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Weekdays: 12:00 PM - 11:00 PM Weekends: 12:00 PM - 12:00 AM</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Whatever is freshest</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Howling Hops Tank Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.52016,-0.0559,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">One Mile End</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://onemileend.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon - Fri 10:30am - 12:00am Sat & Sun 10:30am - 12:00am</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Snakecharmer IPA</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Served at White Hart Brewpub.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="One Mile End" /><input type="submit" value="Get directions" /></form></div>'],
      [51.491698,-0.060028,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Partizan Brewing</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.partizanbrewing.co.uk/home-1">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Open Saturday only: 11am - 5pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">X Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Partizan Brewing" /><input type="submit" value="Get directions" /></form></div>'],
      [51.530129,-0.0569,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Redchurch Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.redchurch.beer/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Monday: CLOSED Tuesday: CLOSED Wendnesday: CLOSED Thursday: 6:00 PM - 12:30 AM Friday: 6:00 PM - 12:30 AM Saturday: 12:00 PM - 12:30 AM Sunday: 6:00 PM - 8:00 PM</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Bethnal Pale Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Redchurch Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.538798,-0.02297,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Trumans Beer</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://www.trumansbeer.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Not sold on-site</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Truman’s Runner</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Offers tours by booking. You can also buy beer directly on their website.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Trumans Beer" /><input type="submit" value="Get directions" /></form></div>'],
      [51.574666,-0.011512,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Brodies Beers</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.brodiesbeers.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Not sold on-site</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Whatever is freshest</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sold at <a href=http://www.brodiesbeers.com/?page_id=2>these</a> locations.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Brodies Beers" /><input type="submit" value="Get directions" /></form></div>'],
      [51.564613,-0.033857,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">East London Brewing Compnay</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.eastlondonbrewing.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Not sold on-site</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">ELB Pale Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sold at <a href=http://www.eastlondonbrewing.com/apps/store-locator/>these</a> locations.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="East London Brewing Compnay" /><input type="submit" value="Get directions" /></form></div>'],
      [51.591723,-0.039281,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Left Bank Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.leftbankbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Not sold on-site</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Moloko Milk Stout</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Small, experimental brewery. You can find their beere <a href=http://www.leftbankbrewery.co.uk/stockists/>here</a>.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Left Bank Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.564416,-0.021801,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Signature Brew</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.signaturebrew.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Open Saturday 12-8</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Roadie</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Brewpub only open on Saturday.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Signature Brew" /><input type="submit" value="Get directions" /></form></div>'],
      [51.583963,-0.008712,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Wild Card Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.wildcardbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Friday - 5pm till Midnight  Saturday - 11am till Midnight Sunday - 11am till 11pm </p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;"></p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Wild Card Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.445823,-0.162359,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Belleville Brewing Co.</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.bellevillebrewing.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Not sold on-site</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Thames Surfer</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sold at <a href=http://www.bellevillebrewing.co.uk/#!stockists>these</a> locations.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Belleville Brewing Co." /><input type="submit" value="Get directions" /></form></div>'],
      [51.432568,-0.184729,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">By The Horns</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://www.bythehorns.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Tuesday: 4pm – 10pm Wednesday: 4pm – 10pm Thursday: 4pm-11pm Friday: 4pm-11pm Saturday: 12pm-11pm Sunday: 2pm – 10pm</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Diamond Geezer</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="By The Horns" /><input type="submit" value="Get directions" /></form></div>'],
      [51.464141,-0.16266,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Laines Brewing @The Four Thieves</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://laines.london/tag/beer">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">MON-THURS: NOON-MIDNIGHT FRI-SAT: NOON-2AM SUN: NOON-10.30PM</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Extra Special Bitter</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sold a the Four Thieves Brewpub.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Laines Brewing @The Four Thieves" /><input type="submit" value="Get directions" /></form></div>'],
      [51.474639,-0.140322,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Mondo Brewing Company</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.mondobrewingcompany.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Monday & Tuesday Closed Wednesday - Friday 17:00 - 23:00 Saturday 14:00 - 22:00 Sunday Closed </p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;"></p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Mondo Brewing Company" /><input type="submit" value="Get directions" /></form></div>'],
      [51.457824,-0.192159,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">The RAM Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.theramquarter.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">MONDAY – FRIDAY 11AM-11PM SATURDAY 9:30AM-11PM SUNDAY 9:30AM – 10.30PM</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Young’s Special London Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Sold through the Youngs Pubs chain.</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="The RAM Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.449317,-0.195635,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Rocky Head Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://sites.google.com/site/rockyheadbrewery/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Not sold on-site</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">Rocky Head Pale Ale</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Rocky Head Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.470009,-0.175974,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Sambrooks Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.sambrooksbrewery.co.uk/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Monday 12:30–6PM Tuesday 12:30–6PM Wednesday 12:30–6PM  Thursday 12:30–6PM Friday 12:30–6PM Saturday 10AM–1PM Sunday Closed </p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;"></p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Sambrooks Brewery" /><input type="submit" value="Get directions" /></form></div>'],
      [51.512949,-0.112964,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Essex Street Brewing Company</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="http://www.templebrewhouse.com/">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">MON – WED 12:00-23:00 THU 12:00-23:30 FRI & SAT 12:00-00:00 SUN 12:00-22:30</p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;">The Gavel</p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: Located in the Temple Brew House</p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Essex Street Brewing Company" /><input type="submit" value="Get directions" /></form></div>'],
      [51.522263,-0.118838,'<div style="width:100%"><h1 style="font-family: Gloria Hallelujah">Bloomsbury Brewery</h1><br /><h4 style="font-family: Coming Soon; margin-top: -20px"><a href="https://www.yelp.com/biz/the-perseverence-london-2">Website</a></h4><div style="display: inline"><h3 style="font-family: Coming Soon; margin-top: -10px">Open on: </h3><p style="font-family: Coming Soon">Mon-Thu 12:00-23:00 Fri 12:00-00:00 Sat 12:00-23:00 Sun 12:00-20:30 </p></div><div style="display: inline; padding-left: 5px"><h3 style="font-family: Coming Soon; margin-top: -10px">Recommended beer: </h3><p style="font-family: Coming Soon;font-size: 1.2em;"></p></div></div><div style="display: block;"><p style="font-family: Coming Soon;font-size: 1.0em; width:200px">Additional notes: </p><div><form action="http://maps.google.com/maps" method="get" target="_blank"><label for="saddr" style="font-family: Coming Soon">Enter your location</label><input type="text" name="saddr" /><input type="hidden" name="daddr" value="Bloomsbury Brewery" /><input type="submit" value="Get directions" /></form></div>'],


    ]);



    var options = {
    icons: {
        default: {
          normal: 'http://icons.iconarchive.com/icons/paomedia/small-n-flat/24/beer-icon.png',
          selected: 'http://icons.iconarchive.com/icons/paomedia/small-n-flat/24/beer-icon.png'
        }
    },
    zoomLevel: 10,
    showTooltip: true,
    showInfoWindow: true,
    useMapTypeControl: true,
    mapType: 'styledMap',
    maps: {
      // Your custom mapTypeId holding custom map styles.
      styledMap: {
        name: 'Styled Map', // This name will be displayed in the map type control.
        styles: [
  {
      "featureType": "administrative",
      "elementType": "labels.text.fill",
      "stylers": [
          {
              "color": "#444444"
          }
      ]
  },
  {
      "featureType": "landscape",
      "elementType": "all",
      "stylers": [
          {
              "color": "#f2f2f2"
          }
      ]
  },
  {
      "featureType": "poi",
      "elementType": "all",
      "stylers": [
          {
              "visibility": "off"
          }
      ]
  },
  {
      "featureType": "road",
      "elementType": "all",
      "stylers": [
          {
              "saturation": -100
          },
          {
              "lightness": 45
          }
      ]
  },
  {
      "featureType": "road.highway",
      "elementType": "all",
      "stylers": [
          {
              "visibility": "simplified"
          }
      ]
  },
  {
      "featureType": "road.arterial",
      "elementType": "labels.icon",
      "stylers": [
          {
              "visibility": "off"
          }
      ]
  },
  {
      "featureType": "transit",
      "elementType": "all",
      "stylers": [
          {
              "visibility": "off"
          }
      ]
  },
  {
      "featureType": "water",
      "elementType": "all",
      "stylers": [
          {
              "color": "#46bcec"
          },
          {
              "visibility": "on"
          }
      ]
  }
]

      }}

    };

// Draw Super Polluter Map

    var map = new google.visualization.Map(document.getElementById('map_markers_div'));
    map.draw(data, options);



  }
